run version check for packaged binaries.
1) "zap --version" display version information for all distros.

  for windows / linux, the binary inside the adapter pack .zap files were
  used.
  for mac, the binary inside /dist/mac were used due to jenkins unzip/zip
  not able to maintain framework symlinks properly and causes zap unable
  to be run properly.

2) backing down electron/electron-builder versions due to crashes

  Prior to reverting, the following error would be thrown via "zap --version"

  FATAL ERROR: Error::Error napi_create_reference

  1: 0x10d3cacd5 node::Buffer::New(v8::Isolate*, char*, unsigned long, void (*)(char*, void*), void*) [/Users/buildengineer/mac-jenkins-slave-tools/jenkins-slave/workspace/version_check_for_electron_crash/dist/mac/zap.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]

  2: 0x10d3cad44 node::Buffer::New(v8::Isolate*, char*, unsigned long, void (*)(char*, void*), void*) [/Users/buildengineer/mac-jenkins-slave-tools/jenkins-slave/workspace/version_check_for_electron_crash/dist/mac/zap.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]

  3: 0x10d3cacf9 node::Buffer::New(v8::Isolate*, char*, unsigned long, void (*)(char*, void*), void*) [/Users/buildengineer/mac-jenkins-slave-tools/jenkins-slave/workspace/version_check_for_electron_crash/dist/mac/zap.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]

  4: 0x10d3a58e8 napi_fatal_error [/Users/buildengineer/mac-jenkins-slave-tools/jenkins-slave/workspace/version_check_for_electron_crash/dist/mac/zap.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]

  5: 0x112d3cc3d Napi::Error::Fatal(char const*, char const*) [/var/folders/v5/0p331z1s1qvfcmv0vjm3kn6w0000gn/T/.zap.id.2I0QU4]

  6: 0x112d4261f Napi::Error::New(napi_env__*) [/var/folders/v5/0p331z1s1qvfcmv0vjm3kn6w0000gn/T/.zap.id.2I0QU4]

  7: 0x112d42cb2 Napi::Function::MakeCallback(napi_value__*, unsigned long, napi_value__* const*, napi_async_context__*) const [/var/folders/v5/0p331z1s1qvfcmv0vjm3kn6w0000gn/T/.zap.id.2I0QU4]

  8: 0x112d54dfd node_sqlite3::Statement::Work_AfterPrepare(napi_env__*, napi_status, void*) [/var/folders/v5/0p331z1s1qvfcmv0vjm3kn6w0000gn/T/.zap.id.2I0QU4]